### ISSUE TITLE
Coma thousands separator

### ISSUE THREAD

**Issue by Xlythe** [Xlythe/Calculator#12]
This would also include spaces every 2 characters in hex and spaces every 4 characters in binary. Include it as an option in settings, defaulted to off. Biggest issue is that the delete key would mess up comas big time. Maybe include them in onDraw? Use the dec-hex-bin code to get numbers out of the equation, and then split at the decimal.

**Comment by Xlythe** [comment]
Added

**Comment by ManIVIctorious** [comment]
Could you please add a configuration, where spaces seperate the thousands in decimal? the separation is needed in hexadecimal and binary, but the commas look a little awkward in some languages...
