### ISSUE TITLE
negative Numbers in Matrix Multiplications

### ISSUE THREAD

**Issue by Xlythe** [Xlythe/Calculator#17]
The Calculator can't handle negative Numbers in Matrix Multiplications: e.g. [[1,2][3,4]]x[[-1,2][2,-1]] gives the result: [[NaN,NaN][NaN,NaN]]

-unverified, reported from app store

**Comment by ManIVIctorious** [comment]
I can confirm this problem

**Comment by Xlythe** [comment]
Should be fixed in the version on the app store... I think...
