### ISSUE TITLE
Not able to draw circle graph correctly

### ISSUE THREAD

**Issue by phy25** [Xlythe/Calculator#24]
Try `x^2+y^2=1`. It should be a perfect circle, but as you can see...

Also try `x^2+4y^2=1`...

**Comment by denilsonsa** [comment]
Screenshot:

![2014-11-18 23 36 46](https://cloud.githubusercontent.com/assets/121676/5110556/bcfa9df4-7000-11e4-863e-264266e59bab.png)

**Comment by denilsonsa** [comment]
For people arriving at this GitHub issue, see also this post on G+ community:
https://plus.google.com/+WillHarmon/posts/iLH4HRx6B3N

And my suggestion:

> How fast is it to evaluate the expression? Quite fast? So I have quick-to-implement solution:
> 1. Change the expression so that it equals to zero. (e.g. x²+y²=1 ⇒ x²+y²-1=0)
> 2. For every pixel visible on the screen, compute the value of the left side.
> 3. For every pixel on screen, if the signal of the computed value changes (when compared to the neighbor pixel), then draw a point.
> 
> It is a simple algorithm, although a bit expensive on the CPU. It certainly has some corner cases, but should work fine for the most common expressions. And since the graph is static, I think it is affordable to have this expensive calculation once.
> 
> The amount of computation can be reduced by lowering the resolution (i.e. compute only ¼ of the pixels).

**Comment by vanitasvitae** [comment]
I can't even find a way to type this equation into the app. The native keyboard is hidden and the "equals"-button does not put an "equals" into the equation, but solves immediately.

**Comment by phy25** [comment]
@vanitasvitae That's because the brand new version has removed support for this. You cannot input "Y" or "=".

Thus this should get closed.
