### ISSUE TITLE
Offset problem with floating widget in cm expanded desktop

### ISSUE THREAD

**Issue by leftshift** [Xlythe/Calculator#26]
When dragging the Calculator icon down to delete it, if Cyanogenmod expanded desktop is activated, the circle with cross is shown too far down (see screenshot) 
![screenshot_2014-06-20-01-50-34](https://cloud.githubusercontent.com/assets/1733162/3335374/f9ef0562-f812-11e3-8e78-4992af440cc3.png)

**Comment by Xlythe** [comment]
This is already fixed. Just hasn't been pushed to CM yet.
