### ISSUE TITLE
Calculator 4.3 being reported as Trojan by Avast! Mobile

### ISSUE THREAD

**Issue by ds33** [Xlythe/Calculator#28]
I have the F-Droid build of Calculator 4.3 on my phone and Avast! Mobile just started identifying it as containing a Trojan today. It has been on my phone since July without a previous report. I have also reported this to F-Droid. The specific notice is, "Trojan detected - Android:Revtcp-A [Trj]". I have no idea if this is a false positive or an actual problem.

**Comment by ghost** [comment]
Hi,

virus total check of this file:

https://www.virustotal.com/de/file/af0a3491b20dbf5deee3007abc461e04fd4bf5cdc577ad909a5383ae39d29e43/analysis/1420402961/

1/56 detection rate, so probably a false positive?

**Comment by Xlythe** [comment]
Yea, false positive. Other users are reporting it too, for the Play Store
version.

**Comment by Xlythe** [comment]
Avast says they've fixed the problem.
