### ISSUE TITLE
where is matrix ?

### ISSUE THREAD

**Issue by Amenocy** [Xlythe/Calculator#34]
first i should tank your . 
i see matrix classes and layouts in source code but where is in UI ? 
i change 
switch (v.getId()) {
                    case R.id.btn_advanced:
                        layout = advancedPad;
                        break;
                    case R.id.btn_hex:
                        layout = matrixPad;
                        break;
                    case R.id.btn_matrix:
                        layout = matrixPad;
                        break;
                    case R.id.btn_close:
                        // Special case. This button just closes the tray.
                        showFab();
                        hideTray();
                        return;
                }
this code to see matrix page , but seems it is not ready ?

**Comment by Xlythe** [comment]
Correct, not ready yet
