### ISSUE TITLE
Graphs

### ISSUE THREAD

**Issue by ghost** [Xlythe/Calculator#37]
I'm having a hard time figuring out where I can find the graph feature. 
The app description says you can swipe left and right to access more panels but there's only one at the right with the same options as the standard calculator except for a plus that creates a bar at the bottom that leads to one more panel with with some letters (no x and y though).

**Comment by ghost** [comment]
On version 5.1.1, that is. The previous version has a lot more features

**Comment by Xlythe** [comment]
Open up the green panel and tap on X (in the bottom right)

**Comment by ghost** [comment]
Thanks, thought it'd be in a seperate panel
