### ISSUE TITLE
What's the status of this version vs CyanogenMod and the lost v4.3 functionality ?

### ISSUE THREAD

**Issue by johnlane** [Xlythe/Calculator#45]
I have version 4.3 which I have been using happily since 2014 in blissful unawareness of later versions - thanks for a great app!

Now, having just installed CM 12.1 on a spare device, I expected to see the same old calculator but I didn't. 

So it looks some of the nice functions (e.g. matrix) in 4.3 disappeared with the [merge with lollipop code](https://github.com/Xlythe/Calculator/commit/c43a0e6bc7bd9d5bded0790633aa731f36893f3f) and the CM version diverged from this one shortly after (nov 2014?).

If I sideload my 4.3 apk, the Google Play Store wants to update it to 5.1.1 (but I've set the Play Store not to update).

I'm confused because 4.3 (`com.android2.calculator3`) appears richer (therefore better?) than the latest here (`com.android2.calculator3` version 5.1.1) and the latest bundled with CM (`com.android.calculator2` version 5.1.1-eb9065775b).

So I just wonder what's happening. 
- What are the differences between the version here and [the one on CM](https://github.com/CyanogenMod/android_packages_apps_Calculator)? 
- Is the functional line in 4.3 going to be reinstated at some point and is that going to become the CM standard. 

I'm not complaining, just interested. Thanks for the great app.

_([4.3 is accessible on F-Droid](https://f-droid.org/repository/browse/?fdid=com.android2.calculator3) for anyone interested)_

**Comment by Xlythe** [comment]
You're pretty much spot on. Updating to 5.0 (lollipop) lost matrix support, but gained multi-graphing and functions (as paid / closed source features) and wear app support. I've been meaning to add matrix support back, but doing it right is a large endeavor... That said, 4.3 is still available on the Play Store [here](https://play.google.com/store/apps/details?id=com.xlythe.calculator.holo) and its full source code is still hosted here under /legacy-mobile.

The version of Calculator hosted here (under /mobile) is 5.0 without the paid features. It should have better graphing and history than CM's copy, though I haven't flashed CM in a while so my knowledge may be out of date.

**Comment by johnlane** [comment]
Thanks for the Play Store [link](https://play.google.com/store/apps/details?id=com.xlythe.calculator.holo) to 4.3, although it shows its version as 1.0.4. I might switch to this version to avoid receiving accidintal updates to the other one.

Interestingly, I did also find [this](https://play.google.com/store/apps/details?id=com.smartapp.calculator2&hl=en) which seems to be a fork of yours, but without any open-source links.
